### ISSUE TITLE
Acrylic Markdown最近什么情况呢？·

### ISSUE THREAD

**Issue by 1acheng** [Richasy/Acrylic-Markdown-Resource#1]
提示3月1日升级~

然后就打不开软件了，一直闪退~  直到今天再次打开，发现物是人非了。

感觉不像是升级，反而是倒退啊。

原有的Windows Hello、 OneDrive同步等功能全没了。

界面还不如之前好看。。。

为什么要这样呢？

**Comment by 1acheng** [comment]
@Richasy

**Comment by Richasy** [comment]
原有的编辑器并不适合做大量文档的管理。这次更新也是依从这个点进行的重新设计。
同时为了能够适应多种终端，也是尽可能地将整个UI结构打散，从实际观感上或许不如上一个版本精致，但会更实用。
关于Windows Hello，从实际应用上来说，并不是很有必要。这次也为每个项目单独提供了密码选项，需要的话可以按需加密。
OneDrive同步砍掉则是因为在国内的体验很差，而且将文档建立在OneDrive文件夹，修改后即可同步，这本身是WIN10的特性之一，从这一点上，OneDrive的使用与本地文件夹的使用并没有区别，也没有必要多此一举。
这次更新主要瞄准的方向还是增强写作的体验。

**Comment by 1acheng** [comment]
能否提供上一个版本~  真的挺喜欢上个版本：）

**Comment by Richasy** [comment]
😢 
也罢，把邮箱给我吧

**Comment by 1acheng** [comment]
ac@ionosphere.cn  谢谢：）
